### ISSUE TITLE
License

### ISSUE THREAD

**Issue by PhilJbt** [YesUseY/Norwegian-language-verbs-training-program#1]
Could you please tell under which license this repository is?
Especially the file [main/data.txt](https://github.com/YesUseY/Norwegian-language-verbs-training-program/blob/main/data.txt).

**Comment by YesUseY** [comment]
It is just my own program in C++ (words are taken from my personal list).

**Comment by PhilJbt** [comment]
I am interested in this file for a project, I may need it in the future. But for me to be able to use it, the license would have to be officially determined in the repository, for legal reasons.

**Comment by YesUseY** [comment]
I have added the license.txt file with MIT license. I think it will be okay :)

**Comment by PhilJbt** [comment]
That's perfect, thanks for being so quick!

**Comment by YesUseY** [comment]
You're welcome!
